function show_v842_goals()
%SHOW_V842_GOALS Prints v8.4.2 target metrics.
T = table( ...
    ["Daily operating cost"; "Deterministic DR success"; "Deterministic feasible DR success"; ...
     "Deterministic VPP RMSE"; "Deterministic terminal SOC error"; "Peak grid import"; ...
     "Hard action clipping"; "Stochastic feasible DR success"], ...
    ["lower than v8.4.1, ideally 2500-2700 $"; "100%"; "100%"; ...
     "<= 70-80 kW"; "<= 1%"; "<= 1300-1400 kW"; ...
     "<= 10-15%"; ">= 99%"], ...
    'VariableNames', {'Metric','Target'});
disp(T);
end
